CREATE TABLE tags (
    id SERIAL PRIMARY KEY,
    type VARCHAR(255),
    tag VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);