create extension if not exists "vector" with schema "public" version '0.5.1';

create table "public"."file_groups" (
    "id" bigint generated by default as identity not null,
    "file_id" uuid not null,
    "group_id" uuid not null,
    "created_at" timestamp with time zone default (now() AT TIME ZONE 'utc'::text)
);


create table "public"."group_tags" (
    "id" bigint generated by default as identity not null,
    "group_id" uuid not null,
    "tag_id" bigint not null,
    "created_at" timestamp with time zone default (now() AT TIME ZONE 'utc'::text)
);


create table "public"."groups" (
    "id" uuid not null default gen_random_uuid(),
    "title" text not null,
    "description" text,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
);


alter table "public"."file_tags" add column "created_at" timestamp with time zone default (now() AT TIME ZONE 'utc'::text);

alter table "public"."tags" add column "featured" boolean;

CREATE UNIQUE INDEX file_groups_pkey ON public.file_groups USING btree (id);

CREATE UNIQUE INDEX group_tags_pkey ON public.group_tags USING btree (id);

CREATE UNIQUE INDEX groups_pkey ON public.groups USING btree (id);

CREATE UNIQUE INDEX tags_tag_key ON public.tags USING btree (tag);

alter table "public"."file_groups" add constraint "file_groups_pkey" PRIMARY KEY using index "file_groups_pkey";

alter table "public"."group_tags" add constraint "group_tags_pkey" PRIMARY KEY using index "group_tags_pkey";

alter table "public"."groups" add constraint "groups_pkey" PRIMARY KEY using index "groups_pkey";

alter table "public"."file_groups" add constraint "public_file_groups_file_id_fkey" FOREIGN KEY (file_id) REFERENCES files(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."file_groups" validate constraint "public_file_groups_file_id_fkey";

alter table "public"."file_groups" add constraint "public_file_groups_group_id_fkey" FOREIGN KEY (group_id) REFERENCES groups(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."file_groups" validate constraint "public_file_groups_group_id_fkey";

alter table "public"."group_tags" add constraint "public_group_tags_group_id_fkey" FOREIGN KEY (group_id) REFERENCES groups(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."group_tags" validate constraint "public_group_tags_group_id_fkey";

alter table "public"."group_tags" add constraint "public_group_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES tags(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."group_tags" validate constraint "public_group_tags_tag_id_fkey";

alter table "public"."tags" add constraint "tags_tag_key" UNIQUE using index "tags_tag_key";

grant delete on table "public"."file_groups" to "anon";

grant insert on table "public"."file_groups" to "anon";

grant references on table "public"."file_groups" to "anon";

grant select on table "public"."file_groups" to "anon";

grant trigger on table "public"."file_groups" to "anon";

grant truncate on table "public"."file_groups" to "anon";

grant update on table "public"."file_groups" to "anon";

grant delete on table "public"."file_groups" to "authenticated";

grant insert on table "public"."file_groups" to "authenticated";

grant references on table "public"."file_groups" to "authenticated";

grant select on table "public"."file_groups" to "authenticated";

grant trigger on table "public"."file_groups" to "authenticated";

grant truncate on table "public"."file_groups" to "authenticated";

grant update on table "public"."file_groups" to "authenticated";

grant delete on table "public"."file_groups" to "service_role";

grant insert on table "public"."file_groups" to "service_role";

grant references on table "public"."file_groups" to "service_role";

grant select on table "public"."file_groups" to "service_role";

grant trigger on table "public"."file_groups" to "service_role";

grant truncate on table "public"."file_groups" to "service_role";

grant update on table "public"."file_groups" to "service_role";

grant delete on table "public"."group_tags" to "anon";

grant insert on table "public"."group_tags" to "anon";

grant references on table "public"."group_tags" to "anon";

grant select on table "public"."group_tags" to "anon";

grant trigger on table "public"."group_tags" to "anon";

grant truncate on table "public"."group_tags" to "anon";

grant update on table "public"."group_tags" to "anon";

grant delete on table "public"."group_tags" to "authenticated";

grant insert on table "public"."group_tags" to "authenticated";

grant references on table "public"."group_tags" to "authenticated";

grant select on table "public"."group_tags" to "authenticated";

grant trigger on table "public"."group_tags" to "authenticated";

grant truncate on table "public"."group_tags" to "authenticated";

grant update on table "public"."group_tags" to "authenticated";

grant delete on table "public"."group_tags" to "service_role";

grant insert on table "public"."group_tags" to "service_role";

grant references on table "public"."group_tags" to "service_role";

grant select on table "public"."group_tags" to "service_role";

grant trigger on table "public"."group_tags" to "service_role";

grant truncate on table "public"."group_tags" to "service_role";

grant update on table "public"."group_tags" to "service_role";

grant delete on table "public"."groups" to "anon";

grant insert on table "public"."groups" to "anon";

grant references on table "public"."groups" to "anon";

grant select on table "public"."groups" to "anon";

grant trigger on table "public"."groups" to "anon";

grant truncate on table "public"."groups" to "anon";

grant update on table "public"."groups" to "anon";

grant delete on table "public"."groups" to "authenticated";

grant insert on table "public"."groups" to "authenticated";

grant references on table "public"."groups" to "authenticated";

grant select on table "public"."groups" to "authenticated";

grant trigger on table "public"."groups" to "authenticated";

grant truncate on table "public"."groups" to "authenticated";

grant update on table "public"."groups" to "authenticated";

grant delete on table "public"."groups" to "service_role";

grant insert on table "public"."groups" to "service_role";

grant references on table "public"."groups" to "service_role";

grant select on table "public"."groups" to "service_role";

grant trigger on table "public"."groups" to "service_role";

grant truncate on table "public"."groups" to "service_role";

grant update on table "public"."groups" to "service_role";


